# Generated by Django 5.1.4 on 2025-01-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
